### ISSUE TITLE
tests don't run on windows

### ISSUE THREAD

**Issue by wabblerjs** [jonschlinkert/nanomatch#1]
_(Thanks for reporting an issue to nanomatch! If you haven't already read the [contributor guidelines](contributing.md), Please do that now, then procede to fill out the details below.)_

## Please describe the **minimum necessary steps** to reproduce this issue:
Run the tests through Windows CMD on a native Windows computer.
…

## What is happening (but shouldn't):
Throws, and all tests breaks. Plus can't find files.

Similar issue as reported here: https://github.com/jonschlinkert/bash-glob/issues/1
…

## What should be happening instead?
Everything should work.
…

**Comment by jonschlinkert** [comment]
what version of windows?

So you're saying you never tried to use the lib, you only tried to run the tests? 

Failing tests don't mean that the lib doesn't work on windows. The tests use bash, which isn't supported on old versions of windows.

**Comment by tunnckoCore** [comment]
@wabblerjs just stop use windows, haha :D It is crap and holded the technologies for years. There are thousand more reasons why windows sucks.

And it's totally normal bash to not work on old windows versions and you should not expect that. You just got the wrong path against Jon. You can't imagine what mistake you did. ;d

**Comment by jonschlinkert** [comment]
all windows tests are passing on appveyor. https://ci.appveyor.com/project/jonschlinkert/nanomatch
